services:

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./mediamtx.yml:/mediamtx.yml:ro
      - ./data/cameras:/cameras

  tapes:
    image: ghcr.io/vicgarcia/tapes:latest
    container_name: tapes
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
      - JWT_KEY=${JWT_KEY}
    env_file:
      - .env
    ports:
      - "8671:8671"
    volumes:
      - ./passwords:/opt/tapes/passwords:ro
      - ./data/cameras:/cameras
    depends_on:
      - mediamtx

networks:

  default:
    name: tapes
    external: false
